name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  vitest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Prepare Nuxt environment
        run: npx nuxt prepare
      - name: Run tests
        run: npx vitest run --reporter=github-actions --reporter=default --coverage
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          if-no-files-found: ignore
